- id: link_dados
  type: stroke  # 'stroke' muda a cor da linha/seta
  metric: 'PortaSFP1'
  thresholds:
    - color: "#22c55e" # Verde (UP)
      level: 1
    - color: "#ef4444" # Vermelho (DOWN)
      level: 0

- id: link_oficina
  type: stroke
  metric: 'PortaSFP3'
  thresholds:
    - color: "#22c55e"
      level: 1
    - color: "#ef4444"
      level: 0
